### ISSUE TITLE
Maven builds fail because they specify a future version

### ISSUE THREAD

**Issue by cmcconomy** [jboss-developer/jboss-picketlink-quickstarts#35]
Current pom entry (in all quickstarts)
`<version.picketlink.javaee.bom>2.8.0.Beta1-SNAPSHOT</version.picketlink.javaee.bom>`

Current latest version on maven central is `2.7.0.Final` -- http://mvnrepository.com/artifact/org.picketlink/picketlink-javaee-6.0

**Comment by pedroigor** [comment]
If you want a specific version, please checkout the corresponding tag. 

The master branch is development thus is always based on SNAPSHOT.
